<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { ElMessage } from 'element-plus'
import { ChatDotRound, Star } from '@element-plus/icons-vue'
import { http } from '@/api/request'

const route=useRoute(),router=useRouter(),loading=ref(false),post=ref<any>(null),comments=ref<any[]>([]),comment=ref(''),sending=ref(false)
const data=(r:any)=>r?.data?.data??r?.data??r??{}
const dateText=(value:string)=>{const date=new Date(value);return Number.isNaN(date.getTime())?'-':date.toLocaleString('zh-CN',{year:'numeric',month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit',hour12:false})}
async function load(){loading.value=true;try{const result=data(await http.get(`/forum/posts/${route.params.id}`));post.value=result.post;comments.value=Array.isArray(result.comments)?result.comments:[]}catch(error:any){ElMessage.error(error?.response?.data?.error||error.message||'信息加载失败')}finally{loading.value=false}}
async function toggle(type:'like'|'favorite'){if(!post.value)return;const state=type==='like'?'is_liked':'is_favorited',count=type==='like'?'like_count':'favorite_count',enabled=!post.value[state];post.value[state]=enabled;post.value[count]=Math.max(0,Number(post.value[count]||0)+(enabled?1:-1));try{const result=data(enabled?await http.post(`/forum/posts/${post.value.id}/${type}`):await http.delete(`/forum/posts/${post.value.id}/${type}`));post.value[count]=Number(result[`${type}_count`]??post.value[count])}catch(error:any){post.value[state]=!enabled;post.value[count]=Math.max(0,Number(post.value[count]||0)+(enabled?-1:1));ElMessage.error(error?.response?.data?.error||error.message||'操作失败')}}
async function send(){if(!comment.value.trim()||sending.value)return;sending.value=true;try{const result=data(await http.post(`/forum/posts/${route.params.id}/comments`,{content:comment.value.trim()}));comments.value=[...comments.value,result.comment];comment.value='';if(post.value)post.value.comment_count=Number(post.value.comment_count||0)+1}catch(error:any){ElMessage.error(error?.response?.data?.error||error.message||'评论失败')}finally{sending.value=false}}
onMounted(load)
</script>

<template><section class="detail" v-loading="loading"><el-button text @click="router.back()">‹ 返回信息广场</el-button><template v-if="post"><article class="post"><header><div class="author"><div class="avatar">{{(post.author?.nickname||'同').slice(0,1)}}</div><div><strong>{{post.author?.nickname||'校园同学'}}</strong><span>{{dateText(post.created_at)}}{{post.location_name?` · ${post.location_name}`:''}}</span></div></div><el-tag effect="plain">{{post.category?.icon||'◉'}} {{post.category?.name||'校园信息'}}</el-tag></header><h2>{{post.title}}</h2><p class="content">{{post.content}}</p><div v-if="post.images?.length" class="images"><img v-for="image in post.images" :key="image" :src="image" alt="帖子图片"/></div><footer><el-button :type="post.is_liked?'danger':'default'" text @click="toggle('like')">♥ {{post.like_count}}</el-button><el-button :icon="Star" :type="post.is_favorited?'warning':'default'" text @click="toggle('favorite')">{{post.favorite_count}}</el-button><span><el-icon><ChatDotRound/></el-icon> {{post.comment_count}} 条评论</span></footer></article><section class="comments"><h3>评论 {{comments.length}}</h3><el-empty v-if="!comments.length" description="还没有评论，来聊聊吧" :image-size="90"/><article v-for="item in comments" :key="item.id" class="comment"><div class="avatar small">{{(item.author?.nickname||'同').slice(0,1)}}</div><div><strong>{{item.author?.nickname||'校园同学'}}</strong><p>{{item.content}}</p><span>{{dateText(item.created_at)}}</span></div></article><div class="comment-box"><el-input v-model="comment" type="textarea" :rows="3" maxlength="300" show-word-limit placeholder="说点什么，友善交流…"/><el-button type="primary" :loading="sending" @click="send">发表评论</el-button></div></section></template></section></template>

<style scoped>.detail{display:grid;gap:16px;max-width:850px}.post,.comments{border:1px solid var(--color-border);border-radius:var(--radius-card);padding:24px;background:var(--color-surface);box-shadow:var(--shadow-sm)}.post header{display:flex;align-items:center;justify-content:space-between;gap:14px}.author{display:flex;align-items:center;gap:10px}.avatar{display:grid;width:40px;height:40px;place-items:center;border-radius:50%;background:#e2f3e6;color:#3c8d61;font-weight:800}.avatar.small{width:34px;height:34px;font-size:13px}.author strong,.author span{display:block}.author strong,.comment strong{color:var(--color-navy);font-size:13px}.author span,.comment span{margin-top:3px;color:var(--color-text-muted);font-size:11px}.post h2{margin:22px 0 10px;color:var(--color-navy);font-size:27px}.content{margin:0;white-space:pre-wrap;color:var(--color-text-secondary);font-size:15px;line-height:1.8}.images{display:grid;gap:10px;margin-top:18px}.images img{max-width:100%;border-radius:10px}.post footer{display:flex;align-items:center;gap:14px;margin-top:18px;padding-top:13px;border-top:1px solid var(--color-border);color:var(--color-text-muted);font-size:13px}.post footer span{display:inline-flex;align-items:center;gap:4px}.comments h3{margin:0 0 15px;color:var(--color-navy);font-size:18px}.comment{display:flex;gap:10px;padding:14px 0;border-top:1px solid var(--color-border)}.comment p{margin:5px 0;color:var(--color-text-secondary);line-height:1.6}.comment-box{display:grid;gap:10px;margin-top:18px}.comment-box :deep(.el-button){justify-self:end}@media(max-width:600px){.post,.comments{padding:17px}.post header{align-items:flex-start;flex-direction:column}}</style>
