<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue'
import { useRouter } from 'vue-router'
import { ElMessage } from 'element-plus'
import { ChatDotRound, EditPen, Search, Star } from '@element-plus/icons-vue'
import { http } from '@/api/request'

type Category = { id:number; code:string; name:string; icon?:string | null }
type Post = { id:number; title:string; content:string; images?:string[]; location_name?:string | null; created_at:string; is_pinned:boolean; author?:{nickname?:string|null}; category?:Category; like_count:number; favorite_count:number; comment_count:number; is_liked:boolean; is_favorited:boolean }
const router=useRouter(),loading=ref(false),categories=ref<Category[]>([]),posts=ref<Post[]>([])
const filters=reactive({categoryId:'',keyword:'',sort:'latest'})
const data=(r:any)=>r?.data?.data??r?.data??r??{}
const dateText=(value:string)=>{const date=new Date(value);return Number.isNaN(date.getTime())?'-':date.toLocaleString('zh-CN',{month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit',hour12:false})}
const filtered=computed(()=>posts.value.filter(post=>!filters.keyword.trim()||`${post.title}${post.content}${post.location_name||''}`.toLowerCase().includes(filters.keyword.trim().toLowerCase())))
async function load(){loading.value=true;try{const [categoryResult,postResult]=await Promise.all([http.get('/forum/categories'),http.get('/forum/posts',{params:{page:1,page_size:40,category_id:filters.categoryId||undefined,sort:filters.sort}})]);const categoryData=data(categoryResult),postData=data(postResult);categories.value=Array.isArray(categoryData.list)?categoryData.list:[];posts.value=Array.isArray(postData.list)?postData.list:[]}catch(error:any){ElMessage.error(error?.response?.data?.error||error.message||'信息广场加载失败')}finally{loading.value=false}}
function setCategory(id=''){filters.categoryId=id;void load()}
function open(id:number){router.push(`/forum/${id}`)}
function publish(){router.push('/forum/publish')}
async function toggle(post:Post,type:'like'|'favorite'){const enabled=type==='like'?!post.is_liked:!post.is_favorited;const state=type==='like'?'is_liked':'is_favorited';const count=type==='like'?'like_count':'favorite_count';(post as any)[state]=enabled;(post as any)[count]=Math.max(0,Number((post as any)[count]||0)+(enabled?1:-1));try{const response=data(enabled?await http.post(`/forum/posts/${post.id}/${type}`):await http.delete(`/forum/posts/${post.id}/${type}`));(post as any)[count]=Number(response[`${type}_count`]??(post as any)[count])}catch(error:any){(post as any)[state]=!enabled;(post as any)[count]=Math.max(0,Number((post as any)[count]||0)+(enabled?-1:1));ElMessage.error(error?.response?.data?.error||error.message||'操作失败')}}
onMounted(load)
</script>

<template><section class="square" v-loading="loading"><header class="hero"><div><span>CAMPUS SQUARE · COMMUNITY</span><h2>校园信息广场</h2><p>失物招领、二手交易、表白墙与校园通知，都在这里发生。</p></div><el-button type="primary" :icon="EditPen" @click="publish">发布信息</el-button></header><section class="filter-panel"><div class="category-list"><el-button :type="!filters.categoryId?'primary':'default'" round @click="setCategory()">全部</el-button><el-button v-for="category in categories" :key="category.id" :type="filters.categoryId===String(category.id)?'primary':'default'" round @click="setCategory(String(category.id))">{{category.icon||'◉'}} {{category.name}}</el-button></div><div class="filter-row"><el-input v-model="filters.keyword" clearable :prefix-icon="Search" placeholder="搜索物品、地点或关键词"/><el-radio-group v-model="filters.sort" @change="load"><el-radio-button label="latest">最新</el-radio-button><el-radio-button label="hot">热门</el-radio-button></el-radio-group></div></section><el-empty v-if="!loading&&!filtered.length" description="暂时没有相关校园信息"><el-button type="primary" @click="publish">发布第一条</el-button></el-empty><main v-else class="post-list"><article v-for="post in filtered" :key="post.id" class="post" @click="open(post.id)"><div class="post-header"><div class="author"><div class="avatar">{{(post.author?.nickname||'同').slice(0,1)}}</div><div><strong>{{post.author?.nickname||'校园同学'}}</strong><span>{{dateText(post.created_at)}}{{post.location_name?` · ${post.location_name}`:''}}</span></div></div><el-tag v-if="post.is_pinned" type="warning" effect="light">置顶</el-tag></div><el-tag effect="plain" class="category">{{post.category?.icon||'◉'}} {{post.category?.name||'校园信息'}}</el-tag><h3>{{post.title}}</h3><p>{{post.content}}</p><div v-if="post.images?.length" class="images"><img v-for="image in post.images.slice(0,3)" :key="image" :src="image" alt="帖子图片"/></div><footer @click.stop><button :class="{active:post.is_liked}" @click="toggle(post,'like')">♥ {{post.like_count}}</button><button @click="open(post.id)"><el-icon><ChatDotRound/></el-icon> {{post.comment_count}}</button><button :class="{active:post.is_favorited}" @click="toggle(post,'favorite')"><el-icon><Star/></el-icon> {{post.favorite_count}}</button><button class="detail" @click="open(post.id)">查看详情 ›</button></footer></article></main></section></template>

<style scoped>.square{display:grid;gap:20px}.hero{display:flex;align-items:center;justify-content:space-between;gap:24px;padding:28px;border-radius:var(--radius-card);background:linear-gradient(135deg,#1f6842,#78b981);color:#fff}.hero span{font-size:11px;font-weight:800;letter-spacing:.12em;opacity:.78}.hero h2{margin:7px 0 5px;font-size:28px;letter-spacing:-.04em}.hero p{margin:0;opacity:.9}.hero :deep(.el-button){flex:0 0 auto}.filter-panel{display:grid;gap:14px;padding:16px;border:1px solid var(--color-border);border-radius:var(--radius-card);background:var(--color-surface)}.category-list{display:flex;flex-wrap:wrap;gap:9px}.filter-row{display:flex;align-items:center;justify-content:space-between;gap:12px}.filter-row :deep(.el-input){max-width:360px}.post-list{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:16px}.post{display:grid;gap:12px;cursor:pointer;border:1px solid var(--color-border);border-radius:var(--radius-card);padding:20px;background:var(--color-surface);box-shadow:var(--shadow-sm);transition:border-color .18s ease,transform .18s ease}.post:hover{transform:translateY(-2px);border-color:#92c3a1}.post-header,.author,footer{display:flex;align-items:center}.post-header{justify-content:space-between;gap:12px}.author{gap:9px}.avatar{display:grid;width:36px;height:36px;place-items:center;border-radius:50%;background:#e2f3e6;color:#378b60;font-size:14px;font-weight:800}.author strong,.author span{display:block}.author strong{color:var(--color-navy);font-size:13px}.author span{margin-top:2px;color:var(--color-text-muted);font-size:11px}.category{justify-self:start}.post h3{margin:0;color:var(--color-navy);font-size:18px}.post p{display:-webkit-box;overflow:hidden;margin:0;color:var(--color-text-secondary);line-height:1.65;-webkit-box-orient:vertical;-webkit-line-clamp:3}.images{display:grid;grid-template-columns:repeat(3,1fr);gap:7px}.images img{width:100%;height:112px;border-radius:9px;object-fit:cover}footer{gap:16px;color:var(--color-text-muted);font-size:12px}footer button{display:inline-flex;align-items:center;gap:4px;border:0;padding:0;background:none;color:inherit;cursor:pointer}footer button.active{color:#d7665b;font-weight:800}.detail{margin-left:auto;color:var(--color-primary)}@media(max-width:760px){.hero{align-items:flex-start;flex-direction:column}.filter-row{align-items:stretch;flex-direction:column}.filter-row :deep(.el-input){max-width:none}.post-list{grid-template-columns:1fr}}</style>
