<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { useRouter } from 'vue-router'
import { ElMessage } from 'element-plus'
import { http } from '@/api/request'
const router=useRouter(), loading=ref(false), keyword=ref(''), merchants=ref<any[]>([])
const visible=computed(()=>merchants.value.filter(v=>!keyword.value.trim()||`${v.name}${v.address}`.includes(keyword.value.trim())))
const data=(r:any)=>r?.data?.data??r?.data??r??{}
async function load(){loading.value=true;try{const r=data(await http.get('/food/merchants',{params:{page:1,page_size:50}}));merchants.value=r.list||[]}catch(e:any){ElMessage.error(e?.response?.data?.error||e.message||'商家加载失败')}finally{loading.value=false}}
onMounted(load)
</script>
<template><section class="food-home"><header><div><span>CAMPUS FOOD</span><h2>校园食堂点餐</h2><p>从商家菜单直接下单，跑腿员为你配送到楼下。</p></div><el-button :loading="loading" @click="load">刷新商家</el-button></header><el-input v-model="keyword" clearable placeholder="搜索食堂、档口或菜品" class="search"/><div v-loading="loading" class="shops"><el-empty v-if="!loading&&!visible.length" description="暂无营业商家"/><article v-for="shop in visible" :key="shop.id" tabindex="0" @click="router.push(`/food/merchant/${shop.id}`)" @keyup.enter="router.push(`/food/merchant/${shop.id}`)"><div class="cover">{{shop.name.slice(0,1)}}</div><div><h3>{{shop.name}} <el-tag size="small" type="success">营业中</el-tag></h3><p>{{shop.description||shop.address}}</p><small>起送 ¥{{Number(shop.min_order_amount||0).toFixed(0)}} · 预计 {{shop.prepare_minutes||15}} 分钟 · {{shop.menu_item_count||0}} 道菜</small></div><b class="arrow">›</b></article></div></section></template>
<style scoped>.food-home{display:grid;gap:20px}.food-home header{display:flex;align-items:end;justify-content:space-between;padding:10px 0 20px;border-bottom:1px solid var(--color-border)}header span{color:var(--color-primary);font-size:11px;font-weight:800;letter-spacing:.12em}h2{margin:5px 0;color:var(--color-navy);font-size:27px}p{margin:0;color:var(--color-text-muted)}.search{max-width:440px}.shops{display:grid;grid-template-columns:repeat(auto-fill,minmax(290px,1fr));gap:16px;min-height:250px}.shops article{display:flex;gap:14px;align-items:center;padding:16px;border:1px solid var(--color-border);border-radius:var(--radius-card);background:var(--color-surface);cursor:pointer;transition:border-color .15s,transform .15s}.shops article:hover,.shops article:focus-visible{border-color:var(--color-primary);outline:0;transform:translateY(-2px)}.cover{display:grid;width:58px;height:58px;flex:none;place-items:center;border-radius:15px;background:#e3f5e9;color:#299566;font-size:26px;font-weight:800}.shops article>div:nth-child(2){min-width:0;flex:1}.shops h3{margin:0;color:var(--color-navy);font-size:16px}.shops p{overflow:hidden;margin:7px 0;text-overflow:ellipsis;white-space:nowrap;font-size:13px}.shops small{color:#629477}@media(max-width:640px){.food-home header{align-items:start;flex-direction:column;gap:14px}}</style>
