<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { ElMessage } from 'element-plus'
import { http } from '@/api/request'
const loading=ref(false),orders=ref<any[]>([]);const data=(r:any)=>r?.data?.data??r?.data??r??{}
const text=(v:string)=>({PAID:'待商家接单',MERCHANT_ACCEPTED:'商家已接单',PREPARING:'备餐中',READY_FOR_PICKUP:'待取餐',ACCEPTED:'配送员已接单',PICKED:'已取餐',DELIVERING:'配送中',DELIVERED:'等待确认',COMPLETED:'已完成',CANCELLED:'已取消',REFUNDED:'已退款'}as any)[v]||v
const itemText=(item:any)=>{const options=Array.isArray(item?.selected_options)?item.selected_options.map((option:any)=>`${option.group_name}:${option.choice_name}`).join('·'):'';return `${item.item_name}${options?`（${options}）`:''}×${item.quantity}`}
async function load(){loading.value=true;try{const r=data(await http.get('/food/orders/my',{params:{page:1,page_size:50}}));orders.value=r.list||[]}catch(e:any){ElMessage.error(e?.response?.data?.error||e.message||'订单加载失败')}finally{loading.value=false}}
async function confirm(id:number){try{await http.post(`/food/orders/${id}/confirm`);ElMessage.success('已确认收餐');load()}catch(e:any){ElMessage.error(e?.response?.data?.error||e.message||'确认失败')}}onMounted(load)
</script>
<template><section class="food-orders"><header><div><span>CAMPUS FOOD · ORDERS</span><h2>我的外卖订单</h2></div><el-button :loading="loading" @click="load">刷新</el-button></header><el-empty v-if="!loading&&!orders.length" description="暂无外卖订单"/><el-table v-else :data="orders" v-loading="loading"><el-table-column label="订单" width="130"><template #default="{row}">{{row.order_no||`#${row.id}`}}</template></el-table-column><el-table-column label="商家" min-width="130"><template #default="{row}">{{row.merchant?.name}}</template></el-table-column><el-table-column label="餐品" min-width="260"><template #default="{row}">{{row.items.map(itemText).join('、')}}</template></el-table-column><el-table-column label="状态" width="130"><template #default="{row}"><el-tag>{{text(row.status)}}</el-tag></template></el-table-column><el-table-column label="金额" width="110"><template #default="{row}">¥{{Number(row.payable_amount||row.total_amount).toFixed(2)}}</template></el-table-column><el-table-column label="操作" width="120"><template #default="{row}"><el-button v-if="row.status==='DELIVERED'" type="success" link @click="confirm(row.id)">确认收餐</el-button></template></el-table-column></el-table></section></template>
<style scoped>.food-orders{display:grid;gap:20px}.food-orders header{display:flex;justify-content:space-between;align-items:end;padding-bottom:18px;border-bottom:1px solid var(--color-border)}header span{color:var(--color-primary);font-size:11px;font-weight:800;letter-spacing:.1em}h2{margin:6px 0 0;color:var(--color-navy);font-size:27px}</style>
