<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { ElMessage } from 'element-plus'
import { http } from '@/api/request'
const route=useRoute(),router=useRouter(), loading=ref(false), saving=ref(false), merchant=ref<any>(null),items=ref<any[]>([]),categories=ref<any[]>([]),cart=reactive<Record<number,number>>({}),address=ref(''),phone=ref('')
const data=(r:any)=>r?.data?.data??r?.data??r??{};const picked=computed(()=>items.value.filter(v=>cart[v.id]).map(v=>({id:v.id,quantity:cart[v.id]})));const amount=computed(()=>items.value.reduce((sum,v)=>sum+Number(v.price)*(cart[v.id]||0),0))
async function load(){loading.value=true;try{const r=data(await http.get(`/food/merchants/${route.params.id}`));merchant.value=r.merchant;items.value=r.menu_items||[];categories.value=r.categories||[]}catch(e:any){ElMessage.error(e?.response?.data?.error||e.message||'菜单加载失败')}finally{loading.value=false}}
async function submit(){if(!picked.value.length)return;if(!address.value.trim())return ElMessage.warning('请填写收餐地点');saving.value=true;try{const created=data(await http.post('/food/orders',{merchant_id:merchant.value.id,items:picked.value,delivery_address:address.value,contact_phone:phone.value})).order;await http.post(`/food/orders/${created.id}/pay`,{});ElMessage.success('支付成功，等待商家接单');router.push('/food/orders')}catch(e:any){ElMessage.error(e?.response?.data?.error||e.message||'下单失败')}finally{saving.value=false}}
onMounted(load)
</script>
<template><section class="food-shop" v-loading="loading"><header v-if="merchant"><div><span>CAMPUS FOOD · MENU</span><h2>{{merchant.name}}</h2><p>{{merchant.announcement||merchant.description||merchant.address}}</p></div><el-tag type="success">预计 {{merchant.prepare_minutes||15}} 分钟备餐</el-tag></header><div class="layout"><section class="menu"><el-empty v-if="!items.length" description="商家暂未上架菜品"/><template v-for="category in categories.length?categories:[{id:null,name:'全部菜品'}]" :key="category.id"><h3>{{category.name}}</h3><article v-for="item in items.filter(v=>!category.id||v.category_id===category.id)" :key="item.id"><div><strong>{{item.name}}</strong><p>{{item.description||'新鲜现做'}}</p><b>¥{{Number(item.price).toFixed(2)}}</b></div><el-input-number v-model="cart[item.id]" :min="0" :max="item.stock<0?99:item.stock" controls-position="right"/></article></template></section><aside class="checkout"><h3>购物车</h3><p>{{picked.length?`${picked.length} 种菜品 · ¥${amount.toFixed(2)}`:'请选择菜品'}}</p><el-input v-model="address" placeholder="收餐地点，例如北区 3 栋 402"/><el-input v-model="phone" placeholder="联系电话（选填）"/><el-button type="primary" :disabled="!picked.length" :loading="saving" @click="submit">钱包支付并下单</el-button><small>另加配送费，支付前将由服务端重新核算。</small></aside></div></section></template>
<style scoped>.food-shop{display:grid;gap:20px}.food-shop header{display:flex;justify-content:space-between;gap:20px;padding-bottom:18px;border-bottom:1px solid var(--color-border)}header span{color:var(--color-primary);font-size:11px;font-weight:800;letter-spacing:.1em}h2{margin:6px 0;color:var(--color-navy);font-size:27px}p{margin:0;color:var(--color-text-muted)}.layout{display:grid;grid-template-columns:minmax(0,1fr) 300px;gap:20px}.menu,.checkout{padding:18px;border:1px solid var(--color-border);border-radius:var(--radius-card);background:var(--color-surface)}.menu h3{margin:6px 0 10px;color:var(--color-navy);font-size:15px}.menu article{display:flex;justify-content:space-between;gap:20px;padding:14px 0;border-top:1px solid var(--color-border)}.menu article>div{min-width:0}.menu strong{color:var(--color-navy)}.menu p{margin:5px 0;font-size:13px}.menu b{color:#dc6b44}.checkout{display:grid;height:max-content;gap:14px;position:sticky;top:16px}.checkout h3{margin:0;color:var(--color-navy)}.checkout small{color:var(--color-text-muted)}@media(max-width:760px){.layout{grid-template-columns:1fr}.checkout{position:static}.food-shop header{flex-direction:column}}</style>
