<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { createCoupon, deleteCoupon, getAdminCoupons, getCouponUsage, giveCoupon, updateCoupon, type Coupon } from '@/api/coupon'

const loading=ref(false),list=ref<Coupon[]>([]),total=ref(0),dialog=ref(false),editing=ref(''),usage=ref<any>(null),usageVisible=ref(false)
const query=reactive({page:1,pageSize:10,keyword:'',status:'',type:''})
const defaults=()=>({name:'',code:'',type:'CASH',value:5,min_order_amount:0,max_discount:0,usage_limit:1,total_limit:0,start_date:'',end_date:'',status:'ACTIVE'})
const form=reactive<any>(defaults())
const giveVisible=ref(false),giveForm=reactive({userId:0,couponId:''})
async function load(){loading.value=true;try{const r=await getAdminCoupons(query);list.value=r.list;total.value=r.total}catch(e:any){ElMessage.error(e?.response?.data?.message||'加载失败')}finally{loading.value=false}}
function open(row?:Coupon){Object.assign(form,defaults(),row||{});editing.value=row?.id||'';if(row){form.start_date=new Date(row.start_date);form.end_date=new Date(row.end_date)}dialog.value=true}
async function save(){try{editing.value?await updateCoupon(editing.value,form):await createCoupon(form);ElMessage.success(editing.value?'修改成功':'创建成功');dialog.value=false;load()}catch(e:any){ElMessage.error(e?.response?.data?.message||'保存失败')}}
async function remove(row:Coupon){await ElMessageBox.confirm(`确认删除“${row.name}”？`,'删除优惠券',{type:'warning'});try{await deleteCoupon(row.id);ElMessage.success('删除成功');load()}catch(e:any){ElMessage.error(e?.response?.data?.message||'删除失败')}}
async function stats(row:Coupon){usage.value=await getCouponUsage(row.id);usageVisible.value=true}
async function give(){try{await giveCoupon(giveForm);ElMessage.success('发放成功');giveVisible.value=false;load()}catch(e:any){ElMessage.error(e?.response?.data?.message||'发放失败')}}
onMounted(load)
</script>
<template><section class="admin-coupons"><header><div><h1>优惠券管理</h1><p>创建、发放并追踪优惠券使用情况。</p></div><div><el-button @click="giveVisible=true">手动发放</el-button><el-button type="success" @click="open()">创建优惠券</el-button></div></header>
<el-card shadow="never"><div class="filters"><el-input v-model="query.keyword" clearable placeholder="名称或优惠码" @keyup.enter="load"/><el-select v-model="query.type" clearable placeholder="类型"><el-option label="现金券" value="CASH"/><el-option label="折扣券" value="DISCOUNT"/></el-select><el-select v-model="query.status" clearable placeholder="状态"><el-option label="启用" value="ACTIVE"/><el-option label="停用" value="DISABLED"/><el-option label="过期" value="EXPIRED"/></el-select><el-button @click="load">查询</el-button></div>
<el-table :data="list" v-loading="loading"><el-table-column prop="name" label="名称" min-width="150"/><el-table-column prop="code" label="优惠码" width="170"/><el-table-column label="类型/面值" width="130"><template #default="{row}">{{row.type==='CASH'?'现金券':'折扣券'}} / {{row.type==='CASH'?'¥':''}}{{row.value}}{{row.type==='DISCOUNT'?'%':''}}</template></el-table-column><el-table-column label="门槛" width="110"><template #default="{row}">¥{{row.min_order_amount}}</template></el-table-column><el-table-column label="领取/总量" width="120"><template #default="{row}">{{row.received_count}} / {{row.total_limit||'不限'}}</template></el-table-column><el-table-column prop="used_count" label="已使用" width="90"/><el-table-column prop="status" label="状态" width="90"/><el-table-column label="操作" width="230" fixed="right"><template #default="{row}"><el-button link type="primary" @click="open(row)">编辑</el-button><el-button link type="success" @click="stats(row)">统计</el-button><el-button link type="danger" @click="remove(row)">删除</el-button></template></el-table-column></el-table><el-pagination v-model:current-page="query.page" v-model:page-size="query.pageSize" :total="total" layout="total, prev, pager, next" @current-change="load"/></el-card>
<el-dialog v-model="dialog" :title="editing?'编辑优惠券':'创建优惠券'" width="640px"><el-form label-width="110px"><el-form-item label="名称"><el-input v-model="form.name"/></el-form-item><el-form-item label="类型"><el-radio-group v-model="form.type"><el-radio-button value="CASH">现金券</el-radio-button><el-radio-button value="DISCOUNT">折扣券</el-radio-button></el-radio-group></el-form-item><el-form-item label="面值"><el-input-number v-model="form.value" :min="0.01" :max="form.type==='DISCOUNT'?100:10000"/></el-form-item><el-form-item label="最低消费"><el-input-number v-model="form.min_order_amount" :min="0" :precision="2"/></el-form-item><el-form-item v-if="form.type==='DISCOUNT'" label="最大优惠"><el-input-number v-model="form.max_discount" :min="0" :precision="2"/></el-form-item><el-form-item label="每人限领"><el-input-number v-model="form.usage_limit" :min="1"/></el-form-item><el-form-item label="发放总量"><el-input-number v-model="form.total_limit" :min="0"/><span class="hint">0 表示不限</span></el-form-item><el-form-item label="有效期"><el-date-picker v-model="form.start_date" type="datetime" placeholder="开始时间"/><span class="dash">—</span><el-date-picker v-model="form.end_date" type="datetime" placeholder="结束时间"/></el-form-item><el-form-item label="状态"><el-switch v-model="form.status" active-value="ACTIVE" inactive-value="DISABLED"/></el-form-item></el-form><template #footer><el-button @click="dialog=false">取消</el-button><el-button type="success" @click="save">保存</el-button></template></el-dialog>
<el-dialog v-model="usageVisible" title="使用统计" width="480px"><div v-if="usage" class="stats"><div><strong>{{usage.received}}</strong><span>已领取</span></div><div><strong>{{usage.used}}</strong><span>已使用</span></div><div><strong>{{usage.remaining??'不限'}}</strong><span>剩余</span></div></div></el-dialog>
<el-dialog v-model="giveVisible" title="手动发放优惠券" width="460px"><el-form label-width="90px"><el-form-item label="用户 ID"><el-input-number v-model="giveForm.userId" :min="1"/></el-form-item><el-form-item label="优惠券"><el-select v-model="giveForm.couponId" placeholder="请选择"><el-option v-for="item in list" :key="item.id" :label="`${item.name}（${item.code}）`" :value="item.id"/></el-select></el-form-item></el-form><template #footer><el-button @click="giveVisible=false">取消</el-button><el-button type="success" :disabled="!giveForm.userId||!giveForm.couponId" @click="give">确认发放</el-button></template></el-dialog>
</section></template>
<style scoped>.admin-coupons header{display:flex;align-items:end;justify-content:space-between;margin-bottom:20px}.admin-coupons h1{margin:0}.admin-coupons p{margin:7px 0 0;color:#64748b}.filters{display:grid;grid-template-columns:2fr 1fr 1fr auto;gap:12px;margin-bottom:18px}.el-pagination{justify-content:flex-end;margin-top:18px}.hint{margin-left:10px;color:#94a3b8}.dash{margin:0 8px}.stats{display:grid;grid-template-columns:repeat(3,1fr);gap:12px}.stats div{display:flex;flex-direction:column;align-items:center;padding:20px;border-radius:14px;background:#f0fdf4}.stats strong{font-size:28px;color:#52c41a}.stats span{margin-top:6px;color:#64748b}@media(max-width:720px){.filters{grid-template-columns:1fr}.admin-coupons header{align-items:flex-start;gap:16px}}</style>
