<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { createCouponEvent, deleteCouponEvent, getAdminCoupons, getCouponEvents, triggerCouponDistribution, updateCouponEvent } from '@/api/coupon'
const list=ref<any[]>([]),coupons=ref<any[]>([]),loading=ref(false),dialog=ref(false),editing=ref('')
const form=reactive<any>({coupon_id:'',trigger_type:'NEW_USER',start_date:null,end_date:null,is_active:true})
const labels:any={NEW_USER:'新人',BIRTHDAY:'生日',HOLIDAY:'节日'}
async function load(){loading.value=true;try{const [e,c]=await Promise.all([getCouponEvents({page:1,pageSize:100}),getAdminCoupons({page:1,pageSize:100})]);list.value=e.list;coupons.value=c.list}finally{loading.value=false}}
function open(row?:any){editing.value=row?.id||'';Object.assign(form,row||{coupon_id:'',trigger_type:'NEW_USER',start_date:null,end_date:null,is_active:true});dialog.value=true}
async function save(){try{editing.value?await updateCouponEvent(editing.value,form):await createCouponEvent(form);ElMessage.success('规则已保存');dialog.value=false;load()}catch(e:any){ElMessage.error(e?.response?.data?.message||'保存失败')}}
async function remove(row:any){await ElMessageBox.confirm(`确认删除“${row.coupon.name}”发放规则？`,'删除规则',{type:'warning'});await deleteCouponEvent(row.id);ElMessage.success('已删除');load()}
async function trigger(){await triggerCouponDistribution();ElMessage.success('自动发放已执行')}
onMounted(load)
</script>
<template><section><header class="head"><div><h1>发放规则</h1><p>按新人、生日或节日自动生成待领取优惠券。</p></div><div><el-button @click="trigger">手动触发测试</el-button><el-button type="success" @click="open()">新增规则</el-button></div></header><el-card shadow="never"><el-table :data="list" v-loading="loading"><el-table-column prop="coupon.name" label="优惠券"/><el-table-column label="触发条件"><template #default="{row}">{{labels[row.trigger_type]}}</template></el-table-column><el-table-column label="生效时间"><template #default="{row}">{{row.start_date?new Date(row.start_date).toLocaleDateString():'立即'}} - {{row.end_date?new Date(row.end_date).toLocaleDateString():'长期'}}</template></el-table-column><el-table-column label="状态"><template #default="{row}"><el-tag :type="row.is_active?'success':'info'">{{row.is_active?'启用':'停用'}}</el-tag></template></el-table-column><el-table-column label="操作" width="150"><template #default="{row}"><el-button link type="primary" @click="open(row)">编辑</el-button><el-button link type="danger" @click="remove(row)">删除</el-button></template></el-table-column></el-table></el-card><el-dialog v-model="dialog" :title="editing?'编辑规则':'新增规则'" width="520px"><el-form label-width="92px"><el-form-item label="优惠券"><el-select v-model="form.coupon_id" style="width:100%"><el-option v-for="c in coupons" :key="c.id" :label="c.name" :value="c.id"/></el-select></el-form-item><el-form-item label="触发类型"><el-select v-model="form.trigger_type" style="width:100%"><el-option v-for="(v,k) in labels" :key="k" :label="v" :value="k"/></el-select></el-form-item><el-form-item label="生效时间"><el-date-picker v-model="form.start_date" type="date" placeholder="开始"/><span class="dash">—</span><el-date-picker v-model="form.end_date" type="date" placeholder="结束"/></el-form-item><el-form-item label="启用"><el-switch v-model="form.is_active"/></el-form-item></el-form><template #footer><el-button @click="dialog=false">取消</el-button><el-button type="success" @click="save">保存</el-button></template></el-dialog></section></template>
<style scoped>.head{display:flex;align-items:end;justify-content:space-between;margin-bottom:20px}.head h1{margin:0}.head p{margin:7px 0 0;color:#64748b}.dash{margin:0 8px}@media(max-width:720px){.head{align-items:flex-start;gap:16px;flex-direction:column}}</style>
