<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { getAdminCoupons, getCouponRecords } from '@/api/coupon'
const list=ref<any[]>([]),total=ref(0),coupons=ref<any[]>([]),loading=ref(false),query=reactive<any>({page:1,pageSize:20,user_id:'',coupon_id:'',dates:[]})
async function load(){loading.value=true;try{const q={...query,start_date:query.dates?.[0],end_date:query.dates?.[1]};const [r,c]=await Promise.all([getCouponRecords(q),getAdminCoupons({page:1,pageSize:100})]);list.value=r.list;total.value=r.total;coupons.value=c.list}finally{loading.value=false}}
function exportCsv(){const rows=[['记录ID','用户ID','用户','优惠券','状态','发放时间','领取时间'],...list.value.map(r=>[r.id,r.user_id,r.user?.nickname||'',r.coupon.name,r.status,r.created_at,r.claimed_at||'待领取'])];const csv='\ufeff'+rows.map(row=>row.map((v:any)=>`"${String(v??'').replaceAll('"','""')}"`).join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));a.download='coupon-records.csv';a.click();URL.revokeObjectURL(a.href)}
onMounted(load)
</script>
<template><section><header class="head"><div><h1>发放记录</h1><p>追踪自动发放、领取和使用状态。</p></div><el-button type="success" plain @click="exportCsv">导出当前数据</el-button></header><el-card shadow="never"><div class="filters"><el-input v-model="query.user_id" clearable placeholder="用户 ID"/><el-select v-model="query.coupon_id" clearable placeholder="优惠券"><el-option v-for="c in coupons" :key="c.id" :label="c.name" :value="c.id"/></el-select><el-date-picker v-model="query.dates" type="daterange" start-placeholder="开始日期" end-placeholder="结束日期"/><el-button type="success" @click="load">查询</el-button></div><el-table :data="list" v-loading="loading"><el-table-column prop="user_id" label="用户 ID" width="90"/><el-table-column label="用户"><template #default="{row}">{{row.user?.nickname||row.user?.phone||'-'}}</template></el-table-column><el-table-column prop="coupon.name" label="优惠券"/><el-table-column prop="status" label="状态"/><el-table-column label="领取状态"><template #default="{row}"><el-tag :type="row.claimed_at?'success':'warning'">{{row.claimed_at?'已领取':'待领取'}}</el-tag></template></el-table-column><el-table-column label="发放时间"><template #default="{row}">{{new Date(row.created_at).toLocaleString()}}</template></el-table-column></el-table><el-pagination v-model:current-page="query.page" :total="total" :page-size="query.pageSize" layout="total,prev,pager,next" @current-change="load"/></el-card></section></template>
<style scoped>.head{display:flex;align-items:end;justify-content:space-between;margin-bottom:20px}.head h1{margin:0}.head p{margin:7px 0 0;color:#64748b}.filters{display:grid;grid-template-columns:140px 1fr 330px auto;gap:12px;margin-bottom:18px}.el-pagination{justify-content:flex-end;margin-top:18px}@media(max-width:900px){.filters{grid-template-columns:1fr}.head{align-items:flex-start;gap:16px}}</style>
