<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { RefreshRight, Search } from '@element-plus/icons-vue'
import { http } from '@/api/request'

type Merchant = { id: number; name: string; address: string; status: string; audit_note?: string | null; commission_rate: number; is_open: boolean; created_at: string; owner?: { nickname?: string; phone?: string }; menu_item_count?: number }
type FoodOrder = { id: number; status: string; total_amount: number; delivery_fee: number; commission_amount: number; created_at: string; merchant?: { name: string }; user?: { nickname?: string; phone?: string }; runner?: { nickname?: string }; items: Array<{ item_name: string; quantity: number }> }

const activeTab = ref('merchants')
const loading = ref(false)
const merchants = ref<Merchant[]>([])
const orders = ref<FoodOrder[]>([])
const merchantTotal = ref(0)
const orderTotal = ref(0)
const merchantQuery = reactive({ page: 1, pageSize: 20, status: 'PENDING', keyword: '' })
const orderQuery = reactive({ page: 1, pageSize: 20, status: '' })
const settings = reactive({ food_delivery_fee: 2, food_platform_commission_rate: 0.1, food_runner_completion_reward: 0 })
const savingSettings = ref(false)

function unwrap(result: any) { return result?.data?.data ?? result?.data ?? result ?? {} }
function errorMessage(error: any) { return error?.response?.data?.error || error?.message || '操作失败，请稍后重试' }
function formatMoney(value: number) { return `¥${Number(value || 0).toFixed(2)}` }
function formatTime(value: string) { const date = new Date(value); return Number.isNaN(date.getTime()) ? '-' : date.toLocaleString('zh-CN', { hour12: false }) }
function merchantStatus(status: string) { return ({ PENDING: '待审核', APPROVED: '已通过', REJECTED: '已驳回', DISABLED: '已停用' } as Record<string, string>)[status] || status }
function orderStatus(status: string) { return ({ PENDING_PAYMENT: '待支付', PAID: '待配送', ACCEPTED: '已接单', PICKED: '已取餐', DELIVERING: '配送中', COMPLETED: '已完成', CANCELLED: '已取消' } as Record<string, string>)[status] || status }
function tagType(status: string) { return ({ PENDING: 'warning', APPROVED: 'success', REJECTED: 'danger', DISABLED: 'info', PENDING_PAYMENT: 'warning', PAID: 'primary', ACCEPTED: 'primary', PICKED: 'primary', DELIVERING: 'primary', COMPLETED: 'success', CANCELLED: 'info' } as Record<string, any>)[status] || 'info' }

async function loadMerchants() { loading.value = true; try { const data = unwrap(await http.get('/admin/food/merchants', { params: { page: merchantQuery.page, page_size: merchantQuery.pageSize, status: merchantQuery.status || undefined, keyword: merchantQuery.keyword.trim() || undefined } })); merchants.value = Array.isArray(data.list) ? data.list : []; merchantTotal.value = Number(data.total || 0) } catch (error) { ElMessage.error(errorMessage(error)) } finally { loading.value = false } }
async function loadOrders() { loading.value = true; try { const data = unwrap(await http.get('/admin/food/orders', { params: { page: orderQuery.page, page_size: orderQuery.pageSize, status: orderQuery.status || undefined } })); orders.value = Array.isArray(data.list) ? data.list : []; orderTotal.value = Number(data.total || 0) } catch (error) { ElMessage.error(errorMessage(error)) } finally { loading.value = false } }
async function loadSettings() { try { Object.assign(settings, unwrap(await http.get('/food/settings'))) } catch (error) { ElMessage.error(errorMessage(error)) } }
async function refresh() { if (activeTab.value === 'merchants') await loadMerchants(); else if (activeTab.value === 'orders') await loadOrders(); else await loadSettings() }

async function audit(row: Merchant, action: 'approve' | 'reject' | 'disable') {
  let note = ''
  try {
    if (action === 'reject') { const result = await ElMessageBox.prompt('请填写驳回原因，商家可在工作台查看。', '驳回商家', { inputType: 'textarea', inputValidator: (value) => Boolean(String(value || '').trim()) || '请填写驳回原因', confirmButtonText: '确认驳回', cancelButtonText: '取消' }); note = String(result.value || '').trim() }
    else await ElMessageBox.confirm(action === 'approve' ? '通过后商家可以营业并上架菜单。' : '停用后商家将不可继续营业。', action === 'approve' ? '通过商家审核' : '停用商家', { type: action === 'approve' ? 'success' : 'warning', confirmButtonText: '确认', cancelButtonText: '取消' })
    await http.put(`/admin/food/merchants/${row.id}/audit`, { action, audit_note: note, commission_rate: row.commission_rate })
    ElMessage.success(action === 'approve' ? '商家已通过' : action === 'reject' ? '商家已驳回' : '商家已停用'); await loadMerchants()
  } catch (error: any) { if (error === 'cancel' || error === 'close') return; ElMessage.error(errorMessage(error)) }
}

async function saveSettings() { savingSettings.value = true; try { await http.put('/admin/food/settings', settings); ElMessage.success('外卖运营配置已保存'); await loadSettings() } catch (error) { ElMessage.error(errorMessage(error)) } finally { savingSettings.value = false } }

onMounted(async () => { await Promise.all([loadMerchants(), loadSettings()]) })
</script>

<template>
  <section class="food-operations">
    <header class="page-heading"><div><span class="eyebrow">CAMPUS FOOD · OPERATIONS</span><h2>校园外卖运营</h2><p>审核商家，查看配送订单，并调整平台抽成规则。</p></div><el-button :icon="RefreshRight" :loading="loading" @click="refresh">刷新</el-button></header>
    <el-tabs v-model="activeTab" @tab-change="refresh">
      <el-tab-pane label="商家审核" name="merchants"><section class="work-panel"><div class="filter-bar"><el-select v-model="merchantQuery.status" clearable placeholder="审核状态" @change="merchantQuery.page = 1; loadMerchants()"><el-option label="待审核" value="PENDING"/><el-option label="已通过" value="APPROVED"/><el-option label="已驳回" value="REJECTED"/><el-option label="已停用" value="DISABLED"/></el-select><el-input v-model="merchantQuery.keyword" clearable placeholder="搜索商家或负责人" @keyup.enter="merchantQuery.page = 1; loadMerchants()"><template #prefix><el-icon><Search /></el-icon></template></el-input><el-button type="primary" @click="merchantQuery.page = 1; loadMerchants()">查询</el-button></div><el-table :data="merchants" v-loading="loading"><el-table-column prop="id" label="ID" width="70"/><el-table-column prop="name" label="商家" min-width="180"><template #default="{ row }"><div class="merchant-cell"><strong>{{ row.name }}</strong><span>{{ row.address }}</span></div></template></el-table-column><el-table-column label="负责人" width="140"><template #default="{ row }">{{ row.owner?.nickname || row.owner?.phone || '-' }}</template></el-table-column><el-table-column label="菜品" width="90"><template #default="{ row }">{{ row.menu_item_count || 0 }}</template></el-table-column><el-table-column label="抽成" width="100"><template #default="{ row }">{{ (row.commission_rate * 100).toFixed(0) }}%</template></el-table-column><el-table-column label="状态" width="105"><template #default="{ row }"><el-tag :type="tagType(row.status)">{{ merchantStatus(row.status) }}</el-tag></template></el-table-column><el-table-column label="申请时间" width="170"><template #default="{ row }">{{ formatTime(row.created_at) }}</template></el-table-column><el-table-column label="操作" width="190" fixed="right"><template #default="{ row }"><el-button v-if="row.status === 'PENDING'" type="success" link @click="audit(row, 'approve')">通过</el-button><el-button v-if="row.status === 'PENDING'" type="danger" link @click="audit(row, 'reject')">驳回</el-button><el-button v-if="row.status === 'APPROVED'" type="warning" link @click="audit(row, 'disable')">停用</el-button><span v-if="row.status !== 'PENDING' && row.status !== 'APPROVED'" class="muted">已处理</span></template></el-table-column></el-table><div class="pagination"><el-pagination v-model:current-page="merchantQuery.page" :page-size="merchantQuery.pageSize" :total="merchantTotal" layout="total, prev, pager, next" @current-change="loadMerchants"/></div></section></el-tab-pane>
      <el-tab-pane label="外卖订单" name="orders"><section class="work-panel"><div class="filter-bar"><el-select v-model="orderQuery.status" clearable placeholder="订单状态" @change="orderQuery.page = 1; loadOrders()"><el-option label="待支付" value="PENDING_PAYMENT"/><el-option label="待配送" value="PAID"/><el-option label="配送中" value="DELIVERING"/><el-option label="已完成" value="COMPLETED"/><el-option label="已取消" value="CANCELLED"/></el-select><el-button type="primary" @click="orderQuery.page = 1; loadOrders()">查询</el-button></div><el-table :data="orders" v-loading="loading"><el-table-column prop="id" label="订单" width="84"><template #default="{ row }">#{{ row.id }}</template></el-table-column><el-table-column label="商家 / 菜品" min-width="230"><template #default="{ row }"><div class="merchant-cell"><strong>{{ row.merchant?.name || '-' }}</strong><span>{{ row.items.map((item: any) => `${item.item_name} ×${item.quantity}`).join('、') }}</span></div></template></el-table-column><el-table-column label="用户" width="120"><template #default="{ row }">{{ row.user?.nickname || row.user?.phone || '-' }}</template></el-table-column><el-table-column label="跑腿员" width="110"><template #default="{ row }">{{ row.runner?.nickname || '-' }}</template></el-table-column><el-table-column label="实付 / 抽成" width="130"><template #default="{ row }">{{ formatMoney(row.total_amount) }}<small>抽成 {{ formatMoney(row.commission_amount) }}</small></template></el-table-column><el-table-column label="状态" width="108"><template #default="{ row }"><el-tag :type="tagType(row.status)">{{ orderStatus(row.status) }}</el-tag></template></el-table-column><el-table-column label="创建时间" width="170"><template #default="{ row }">{{ formatTime(row.created_at) }}</template></el-table-column></el-table><div class="pagination"><el-pagination v-model:current-page="orderQuery.page" :page-size="orderQuery.pageSize" :total="orderTotal" layout="total, prev, pager, next" @current-change="loadOrders"/></div></section></el-tab-pane>
      <el-tab-pane label="抽成与配送费" name="settings"><section class="settings-panel"><div><h3>外卖运营定价</h3><p>新建订单会读取此处配置；已生成订单保留当时的费用快照。完成配送奖励会在跑腿员确认送达时结算。</p></div><el-form label-position="top" class="settings-form"><el-form-item label="基础配送费（元）"><el-input-number v-model="settings.food_delivery_fee" :min="0" :max="100" :precision="2"/></el-form-item><el-form-item label="平台抽成比例"><el-input-number v-model="settings.food_platform_commission_rate" :min="0" :max="0.8" :step="0.01" :precision="2"/><span class="form-help">当前 {{ (settings.food_platform_commission_rate * 100).toFixed(0) }}%</span></el-form-item><el-form-item label="跑腿员完成配送奖励（元）"><el-input-number v-model="settings.food_runner_completion_reward" :min="0" :max="100" :precision="2"/><span class="form-help">在配送费之外额外结算</span></el-form-item><el-button type="primary" :loading="savingSettings" @click="saveSettings">保存运营配置</el-button></el-form></section></el-tab-pane>
    </el-tabs>
  </section>
</template>

<style scoped>
.food-operations { display: grid; gap: 20px; }.page-heading { display: flex; align-items: end; justify-content: space-between; gap: 20px; padding-bottom: 18px; border-bottom: 1px solid var(--color-border); }.eyebrow { color: var(--color-primary); font-size: 11px; font-weight: 850; letter-spacing: .1em; }.page-heading h2 { margin: 6px 0 3px; color: var(--color-navy); font-size: 26px; letter-spacing: -.04em; }.page-heading p, .settings-panel p { margin: 0; color: var(--color-text-muted); font-size: 13px; }.work-panel, .settings-panel { border: 1px solid var(--color-border); border-radius: var(--radius-card); padding: 18px; background: var(--color-surface); box-shadow: var(--shadow-sm); }.filter-bar { display: flex; gap: 10px; margin-bottom: 16px; }.filter-bar :deep(.el-select) { width: 130px; }.filter-bar :deep(.el-input) { width: min(300px, 100%); }.merchant-cell { display: grid; gap: 3px; }.merchant-cell strong, .merchant-cell span { overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }.merchant-cell strong { color: var(--color-navy); }.merchant-cell span, small, .muted { color: var(--color-text-muted); font-size: 12px; }.pagination { display: flex; justify-content: flex-end; margin-top: 18px; }.settings-panel { display: grid; grid-template-columns: minmax(0, .8fr) minmax(300px, 1.2fr); gap: 34px; }.settings-panel h3 { margin: 0 0 8px; color: var(--color-navy); font-size: 19px; }.settings-form { display: grid; grid-template-columns: 1fr 1fr; gap: 14px; align-items: end; }.form-help { margin-left: 8px; color: var(--color-text-muted); font-size: 12px; } @media (max-width: 780px) { .page-heading { align-items: flex-start; flex-direction: column; }.filter-bar { flex-wrap: wrap; }.settings-panel, .settings-form { grid-template-columns: 1fr; } }
</style>
