<script setup lang="ts">
import { onMounted, ref, watch } from 'vue'
import { ElMessage } from 'element-plus'
import { getMyCoupons, type Coupon, type UserCoupon } from '@/api/coupon'
const tab=ref<'UNUSED'|'USED'|'EXPIRED'>('UNUSED'),loading=ref(false),list=ref<UserCoupon[]>([])
const fmt=(v:string)=>new Date(v).toLocaleDateString('zh-CN')
const valueText=(c:Coupon)=>c.type==='CASH'?`¥${Number(c.value).toFixed(2)}`:`${Number(c.value)}折`
const condition=(c:Coupon)=>Number(c.min_order_amount)>0?`满 ¥${Number(c.min_order_amount).toFixed(2)} 可用`:'无门槛'
async function load(){loading.value=true;try{list.value=(await getMyCoupons({page:1,pageSize:100,status:tab.value})).list}catch(e:any){ElMessage.error(e?.response?.data?.message||'优惠券加载失败')}finally{loading.value=false}}
watch(tab,load);onMounted(load)
</script>
<template><section class="coupon-page" v-loading="loading"><header><div><h1>我的优惠券</h1><p>发布任务结算时，可选择满足条件的优惠券抵扣配送费。</p></div></header><el-tabs v-model="tab"><el-tab-pane label="未使用" name="UNUSED"/><el-tab-pane label="已使用" name="USED"/><el-tab-pane label="已过期" name="EXPIRED"/></el-tabs><el-empty v-if="!list.length" description="暂无优惠券"/><div v-else class="coupon-grid"><article v-for="item in list" :key="item.id" class="coupon-card" :class="{muted:item.status!=='UNUSED'}"><div class="coupon-value">{{valueText(item.coupon)}}</div><div class="coupon-info"><strong>{{item.coupon.name}}</strong><span>{{condition(item.coupon)}}</span><small>有效期至 {{fmt(item.expired_at)}}</small></div><RouterLink v-if="item.status==='UNUSED'" class="el-button el-button--success is-round" to="/task/publish">去使用</RouterLink><span v-else class="status">{{item.status==='USED'?'已使用':'已过期'}}</span></article></div></section></template>
<style scoped>.coupon-page{max-width:1080px;margin:auto}.coupon-page header{margin-bottom:18px}.coupon-page h1{margin:0;font-size:28px}.coupon-page p{margin:8px 0 0;color:#64748b}.coupon-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(340px,1fr));gap:18px}.coupon-card{display:grid;grid-template-columns:110px 1fr auto;align-items:center;gap:18px;padding:22px;background:#fff;border:1px solid #dcfce7;border-radius:18px;box-shadow:0 12px 30px rgba(21,128,61,.08)}.coupon-value{font-size:30px;font-weight:800;color:#52c41a;text-align:center}.coupon-info{display:flex;flex-direction:column;gap:6px;border-left:1px dashed #bbf7d0;padding-left:18px}.coupon-info span,.coupon-info small{color:#64748b}.coupon-card.muted{filter:grayscale(.7);opacity:.72}.status{color:#64748b;font-weight:600}@media(max-width:640px){.coupon-card{grid-template-columns:86px 1fr}.coupon-card .el-button,.status{grid-column:2}}</style>
